version: "3.8"

services:
  jenkins:
    image: jenkinsci/spx
    build: ../jenkins/Dockerfile
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins-fw
    networks:
      - sonarnet
    volumes:
      - /data/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/jenkins_home/m2deps:/var/jenkins_home/.m2/repository/
    secrets:
     - bitBucketPassword     
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /data/sonarqube_data:/opt/sonarqube/data
      - /data/sonarqube_extensions:/opt/sonarqube/extensions
      - /data/sonarqube_logs:/opt/sonarqube/logs
      - /data/sonarqube_temp:/opt/sonarqube/temp
  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /data/postgresql:/var/lib/postgresql
      - /data/postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql:
  postgresql_data:
  
secrets:
  bitBucketPassword:
    file: ~/secrets/bitBucketPWD